-- Production-like local seed.
--
-- The application no longer seeds fabricated scores, claims, purchases, or
-- golfers. Apply schema.sql, then roster.sql, to load the real Aug 8 roster
-- while leaving all day-of activity tables empty.
